database:
  HOST: '101.43.25.73'
  USER: 'root'
  PASSWORD: ''
  DATABASE: 'arknightsbotresource'
baiduocr:
  APP_NAME: 'MisakaTranslator'
  APP_ID: '24759035'
  API_KEY: 't8EPsuHfpd66XBEgvYYmaovs'
  SECRET_KEY: 'QV1k69ESZUZCyo9m5WTNlsC3a4H6S6ai'
welcome:
  GROUPS:
    - 645350897
autopicsave:
  GROUPS:
    - 645350897
bilibilidynamic:
  accounts:
    - UID: 161775300
      GROUPS:
        - 645350897