database:
  HOST:
  USER:
  PASSWORD:
  DATABASE:
baiduocr:
  APP_NAME:
  APP_ID:
  API_KEY:
  SECRET_KEY:
welcome:
  GROUPS:
    - 
autopicsave:
  GROUPS:
    - 
bilibilidynamic:
  accounts:
    - UID: 
      GROUPS:
        - 
